= Antq

Point out your outdated dependencies.

image:https://github.com/liquidz/antq/workflows/test/badge.svg["GitHub Actions for test workflow", link="https://github.com/liquidz/antq/actions?query=workflow%3Atest"]
image:https://github.com/liquidz/antq/workflows/lint/badge.svg["GitHub Actions for lint workflow", link="https://github.com/liquidz/antq/actions?query=workflow%3Alint"]
image:https://github.com/liquidz/antq/workflows/dependencies/badge.svg["GitHub Actions for dependencies workflow", link="https://github.com/liquidz/antq/actions?query=workflow%3Adependencies"]
image:https://codecov.io/gh/liquidz/antq/branch/master/graph/badge.svg["codecov", link="https://codecov.io/gh/liquidz/antq"]

image:https://img.shields.io/clojars/v/antq.svg["Clojars Project", link="https://clojars.org/antq"]
image:https://img.shields.io/badge/docker-automated-blue["Docker Hub", link="https://hub.docker.com/r/uochan/antq"]

NOTE: Antq requires Clojure 1.8.0 or later.  If you'd like to use with 1.7.0 or earlier, please see link:./doc/clojure-1.7.adoc[here].

== Supported files

* deps.edn (https://clojure.org/guides/deps_and_cli[Clojure CLI])
* shadow-cljs.edn (http://shadow-cljs.org[Shadow-cljs])
* project.clj (https://leiningen.org[Leiningen])
* build.boot (https://boot-clj.com[Boot])
* pom.xml (https://maven.apache.org[Maven])
* .github/workflows/*.yml (https://github.com/features/actions[GitHub Actions])

== Usage

=== Clojure CLI Tool

Run the following command for trial.
[source,clojure]
----
clojure -Sdeps '{:deps {antq/antq {:mvn/version "RELEASE"}}}' -m antq.core
----

Or add the following alias to your `$HOME/.clojure/deps.edn`.
[source,clojure]
----
{
 :aliases
 {:outdated {:extra-deps {antq/antq {:mvn/version "RELEASE"}}
             :main-opts ["-m" "antq.core"]}}
 }
----
Then, run `clojure -M:outdated`.
(run `clojure -A:outdated` for Clojure CLI Tool 1.10.1.645 or earlier).

=== Leiningen

Add the following dependency and alias to your `$HOME/.lein/profiles.clj`.
[source,clojure]
----
{
 :user
 {:dependencies [[antq/antq "RELEASE"]]
  :aliases {"outdated" ["run" "-m" "antq.core"]}
  }
 }
----
Then, run `lein outdated`.

=== GitHub Actions

Antq can work with https://github.com/features/actions[GitHub Actions].
See antq's workflow for concrete example.

* https://github.com/liquidz/antq/blob/master/.github/workflows/dependencies.yml[.github/workflows/dependencies.yml]
* To show errors as annotations, please set this option: `--error-format="::error file={{file}}::{{message}}"`

== Options
=== --upgrade
Upgrade outdated versions interactively.
You can use `--force` option for upgrading without confirmation.

[WARNING]
====
For now, `--upgrade` option only supports following files.

* deps.edn
* shadow-cljs.edn
* project.clj
* pom.xml
====

=== --exclude=ARTIFACT_NAME
Skip version checking for specified artifacts.

E.g. `--exclude=antq/antq`

NOTE: You must specify `groupId/artifactId` for Java dependencies.

=== --directory=DIRECTORY
Add search path for projects.
Current directory(`.`) is added by default.

E.g. `-d foo --directory=bar:baz` will search "foo", "baz" and "bar" directories.

=== --skip=PROJECT
Skip to search specified project files.
Must be one of `boot`, `clojure-cli`, `github-action`, `pom`, `shadow-cljs` and `leiningen`.

E.g. `--skip=pom`

=== --error-format=ERROR_FORMAT
Customize outputs for outdated dependencies.

E.g.  `--error-format="::error file={{file}}::{{message}}"`

You can use following variables:

|===
| Variable Name | Description

| `{{file}}`
| A filename containing outdated dependencies.

| `{{name}}`
| The artifact name.

| `{{version}}`
| The current version.

| `{{latest-version}}`
| The latest version.

| `{{message}}`
| Default error message.

|===

=== --reporter=REPORTER

|===
| Reporter Name | Description

| `table` (default)
| Report results in a table.

| `format`
| Report results with a custom format.
When you use `--error-format` option, this reporter will be used automatically.

| `json`
| Report results as a JSON format.

| `edn`
| Report results as a EDN format.

|===

== Tips

* link:./doc/maven-s3-repos.adoc[Maven S3 reposhere].
* link:./doc/avoid-slf4j-warnings.adoc[Avoid SLF4J warnings]
* link:./doc/latest-version-of-a-specific-library.adoc[Latest version of a specific library]
* link:./doc/clojure-1.7.adoc[Antq with Clojure 1.7.0 or earlier]

== License

Copyright © 2020 https://twitter.com/uochan[Masashi Iizuka]

This program and the accompanying materials are made available under the
terms of the Eclipse Public License 2.0 which is available at
http://www.eclipse.org/legal/epl-2.0.

This Source Code may also be made available under the following Secondary
Licenses when the conditions for such availability set forth in the Eclipse
Public License, v. 2.0 are satisfied: GNU General Public License as published by
the Free Software Foundation, either version 2 of the License, or (at your
option) any later version, with the GNU Classpath Exception which is available
at https://www.gnu.org/software/classpath/license.html.
