= Antq

Point out your outdated dependencies.

image:https://github.com/liquidz/antq/workflows/test/badge.svg["GitHub Actions for test workflow", link="https://github.com/liquidz/antq/actions?query=workflow%3Atest"]
image:https://github.com/liquidz/antq/workflows/lint/badge.svg["GitHub Actions for lint workflow", link="https://github.com/liquidz/antq/actions?query=workflow%3Alint"]
image:https://github.com/liquidz/antq/workflows/dependencies/badge.svg["GitHub Actions for dependencies workflow", link="https://github.com/liquidz/antq/actions?query=workflow%3Adependencies"]
image:https://codecov.io/gh/liquidz/antq/branch/master/graph/badge.svg["codecov", link="https://codecov.io/gh/liquidz/antq"]

image:https://img.shields.io/clojars/v/antq.svg["Clojars Project", link="https://clojars.org/antq"]
image:https://img.shields.io/badge/docker-automated-blue["Docker Hub", link="https://hub.docker.com/r/uochan/antq"]

== Supported files

* deps.edn (https://clojure.org/guides/deps_and_cli[Clojure CLI])
* shadow-cljs.edn (http://shadow-cljs.org[Shadow-cljs])
* project.clj (https://leiningen.org[Leiningen])
* build.boot (https://boot-clj.com[Boot])
* pom.xml (https://maven.apache.org[Maven])
* .github/workflows/*.yml (https://github.com/features/actions[GitHub Actions])

== Usage

=== Clojure CLI Tool

Add following alias to your `$HOME/.clojure/deps.edn`.
[source,clojure]
----
{
 :aliases
 {:outdated {:extra-deps {antq {:mvn/version "RELEASE"}}
             :main-opts ["-m" "antq.core"]}}
 }
----
Then, run `clojure -A:outdated`.

=== Leiningen

Add following dependency and alias to your `$HOME/.lein/profiles.clj`.
[source,clojure]
----
{
 :user
 {:dependencies [[antq "RELEASE"]]
  :aliases {"outdated" ["run" "-m" "antq.core"]}
  }
 }
----
Then, run `lein outdated`.

=== GitHub Actions

Antq can work with https://github.com/features/actions[GitHub Actions].
See antq's workflow for concrete example.

* https://github.com/liquidz/antq/blob/master/.github/workflows/dependencies.yml[.github/workflows/dependencies.yml]
* To show errors as annotations, please set this option: `--error-format="::error file={{file}}::{{message}}"`

== License

Copyright © 2020 https://twitter.com/uochan[Masashi Iizuka]

This program and the accompanying materials are made available under the
terms of the Eclipse Public License 2.0 which is available at
http://www.eclipse.org/legal/epl-2.0.

This Source Code may also be made available under the following Secondary
Licenses when the conditions for such availability set forth in the Eclipse
Public License, v. 2.0 are satisfied: GNU General Public License as published by
the Free Software Foundation, either version 2 of the License, or (at your
option) any later version, with the GNU Classpath Exception which is available
at https://www.gnu.org/software/classpath/license.html.
