= Antq

Point out your outdated dependencies.

image:https://github.com/liquidz/antq/workflows/test/badge.svg["GitHub Actions for test workflow", link="https://github.com/liquidz/antq/actions?query=workflow%3Atest"]
image:https://github.com/liquidz/antq/workflows/lint/badge.svg["GitHub Actions for lint workflow", link="https://github.com/liquidz/antq/actions?query=workflow%3Alint"]
image:https://github.com/liquidz/antq/workflows/dependencies/badge.svg["GitHub Actions for dependencies workflow", link="https://github.com/liquidz/antq/actions?query=workflow%3Adependencies"]
image:https://codecov.io/gh/liquidz/antq/branch/master/graph/badge.svg["codecov", link="https://codecov.io/gh/liquidz/antq"]

image:https://img.shields.io/clojars/v/antq.svg["Clojars Project", link="https://clojars.org/antq"]
image:https://img.shields.io/badge/docker-automated-blue["Docker Hub", link="https://hub.docker.com/r/uochan/antq"]

== Supported files

* deps.edn (https://clojure.org/guides/deps_and_cli[Clojure CLI])
* shadow-cljs.edn (http://shadow-cljs.org[Shadow-cljs])
* project.clj (https://leiningen.org[Leiningen])
* build.boot (https://boot-clj.com[Boot])
* pom.xml (https://maven.apache.org[Maven])
* .github/workflows/*.yml (https://github.com/features/actions[GitHub Actions])

== Usage

=== Clojure CLI Tool

Run the following command for trial.
[source,clojure]
----
clojure -Sdeps '{:deps {antq {:mvn/version "RELEASE"}}}' -m antq.core
----

Or add following alias to your `$HOME/.clojure/deps.edn`.
[source,clojure]
----
{
 :aliases
 {:outdated {:extra-deps {antq {:mvn/version "RELEASE"}}
             :main-opts ["-m" "antq.core"]}}
 }
----
Then, run `clojure -A:outdated`.

=== Leiningen

Add following dependency and alias to your `$HOME/.lein/profiles.clj`.
[source,clojure]
----
{
 :user
 {:dependencies [[antq "RELEASE"]]
  :aliases {"outdated" ["run" "-m" "antq.core"]}
  }
 }
----
Then, run `lein outdated`.

=== GitHub Actions

Antq can work with https://github.com/features/actions[GitHub Actions].
See antq's workflow for concrete example.

* https://github.com/liquidz/antq/blob/master/.github/workflows/dependencies.yml[.github/workflows/dependencies.yml]
* To show errors as annotations, please set this option: `--error-format="::error file={{file}}::{{message}}"`

== Options
=== --exclude=ARTIFACT_NAME
Skip version cheking for specified artifacts.
E.g. `--exclude=antq/antq`

NOTE: You must specify `groupId/artifactId` for Java dependencies.

=== --error-format=ERROR_FORMAT
Customize outputs for outdated dependencies.
E.g.  `--error-format="::error file={{file}}::{{message}}"`

You can use following variables:

|===
| Variable Name | Description

| `{{file}}`
| A filename containing outdated dependencies.

| `{{name}}`
| The artifact name.

| `{{version}}`
| The current version.

| `{{latest-version}}`
| The latest version.

| `{{message}}`
| Default error message.

|===

=== --reporter=REPORTER

|===
| Reporter Name | Description

| `table` (default)
| Report results in a table.

| `format`
| Report results with a custom format.
When you use `--error-format` option, this reporter will be used automatically.

| `json`
| Report resulta as a JSON format.

| `edn`
| Report resulta as a EDN format.

|===

== Tips

=== Maven S3 repos

Antq supports Maven S3 repositories as same as https://clojure.org/reference/deps_and_cli[tools.deps].
To use Maven S3 repositories, add repositories to your project configration.

Please see https://clojure.org/reference/deps_and_cli#_maven_s3_repos[tools.deps documents] documents for AWS S3 credentials.

.Clojure CLI Tool (deps.edn)
[source,clojure]
----
{:deps {...}
 :mvn/repos {"my-private-repo" {:url "s3://my-bucket/maven/releases"}}
----

.Leiningen (project.clj)
[source,clojure]
----
(defproject foo "0.1.0-SNAPSHOT"
  :dependencies [...]
  :repositories [["my-private-repo" {:url "s3://my-bucket/maven/releases"}]])
----

.Boot (build.boot)
[source,clojure]
----
(set-env!
  :repositories #(conj % '["my-private-repo" {:url "s3://my-bucket/maven/releases"}]))
----

== License

Copyright © 2020 https://twitter.com/uochan[Masashi Iizuka]

This program and the accompanying materials are made available under the
terms of the Eclipse Public License 2.0 which is available at
http://www.eclipse.org/legal/epl-2.0.

This Source Code may also be made available under the following Secondary
Licenses when the conditions for such availability set forth in the Eclipse
Public License, v. 2.0 are satisfied: GNU General Public License as published by
the Free Software Foundation, either version 2 of the License, or (at your
option) any later version, with the GNU Classpath Exception which is available
at https://www.gnu.org/software/classpath/license.html.
